extends: airbnb-base

rules:
  no-underscore-dangle: off
  no-console: off
  import/no-extraneous-dependencies: off
  max-len:
    - error
    - code: 120
      ignoreRegExpLiterals: true

env:
  jest: true
  browser: true
