name: NPM Publish

env:
  NODE_VERSION: 16

on:
  push:
    tags: v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{env.NODE_VERSION}}
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run build
      - run: npm publish dist/
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
