name: Tests

on:
  push:
    branches: master

env:
  CI: true
  NODE_VERSION: 12

jobs:
  test:
    name: Jest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: node --version
      - run: npm --version

      - name: NPM Install
        run: npm ci

      - name: Run Jest Tests
        run: npm run test --if-present
        env:
          NODE_ENV: test

  build:
    name: Rollup
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: node --version
      - run: npm --version

      - name: NPM Install
        run: npm ci

      - name: Run Rollup build
        run: npm run build --if-present
