name: Tests

on:
  push:
    branches: master
  pull_request:
    branches: master

env:
  NODE_VERSION: 20

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: NPM Install
        run: npm ci

      - name: Run Jest Tests
        run: npm run test --if-present
        env:
          NODE_ENV: test

  build:
    name: Rollup
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: NPM Install
        run: npm ci

      - name: Run Rollup build
        run: npm run build --if-present
